FROM node:20.10.0-alpine3.19

LABEL author="Tan Nguyen"
LABEL version="1.0.00"
LABEL description="Docker image for Node.js"

# install build dependencies and needed tools
RUN apk add \
    bash \
    wget \
    gcc \
    g++ \
    make \
    zlib-dev \
    libffi-dev \
    openssl-dev \
    musl-dev

WORKDIR /app

#RUN yarn --version

#COPY package.json yarn.lock ./
#RUN yarn install
#COPY . .
#RUN yarn build

EXPOSE 3000

CMD ["sleep", "infinity"]
#CMD ["yarn", "start"]
